# Generated by Django 3.0.8 on 2020-07-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB2_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='duongdan_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duongdan', models.FileField(upload_to='sharefile/vanban/')),
            ],
        ),
    ]
