# Generated by Django 3.0.8 on 2020-07-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB2_APP', '0002_duongdan_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='duongdan_m',
            name='tenfile',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
