# Generated by Django 3.0.8 on 2020-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB2_APP', '0003_duongdan_m_tenfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='duongdan_m',
            name='ngayup',
            field=models.DateField(null=True),
        ),
    ]
