# Generated by Django 3.0.8 on 2020-07-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB2_APP', '0004_duongdan_m_ngayup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duongdan_m',
            name='ngayup',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
