# Generated by Django 3.0.8 on 2020-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB2_APP', '0005_auto_20200710_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='duongdan_m',
            name='nguoiupload',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
