# Generated by Django 3.0.8 on 2020-07-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLVB2_APP', '0006_duongdan_m_nguoiupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duongdan_m',
            name='duongdan',
            field=models.FileField(upload_to=''),
        ),
    ]
