# Generated by Django 3.1 on 2020-08-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offenses',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('offensenID', models.IntegerField()),
                ('domainID', models.IntegerField()),
                ('descriptions', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=200)),
                ('sourceIP', models.GenericIPAddressField()),
                ('destinationIP', models.GenericIPAddressField()),
                ('severity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainName', models.CharField(max_length=100)),
                ('domainID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DomainName2Offenses', to='JobManager.offenses')),
            ],
        ),
    ]
