# Generated by Django 3.1 on 2020-08-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainname',
            name='id',
        ),
        migrations.AlterField(
            model_name='domainname',
            name='domainID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offenses',
            name='domainID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DomainName2Offenses', to='JobManager.domainname'),
        ),
    ]
