# Generated by Django 3.1 on 2020-08-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobManager', '0002_auto_20200820_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offenses',
            name='domainID',
        ),
        migrations.DeleteModel(
            name='DomainName',
        ),
        migrations.DeleteModel(
            name='Offenses',
        ),
    ]
